
name: Upload Python Package

on:
    release:
        types: [published]

jobs:
    pypi-publish:
        name: Publish to PyPi
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/nettime-py
        permissions:
            id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
        steps:
            - uses: actions/checkout@v3 # Checking out the repo
            - name: Set up Python
              uses: actions/setup-python@v4
              with: 
                python-version: '3.10'
            - name: Build package version
              run: |
                pip install -r requirements.txt
                pip install twine setuptools wheel
                python setup.py sdist bdist_wheel
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1